<?php

/**
 * BaseTema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $first_post_id
 * @property integer $foro_id
 * @property Foro $Foro
 * @property Post $Post
 * @property Doctrine_Collection $Posts
 * 
 * @method integer             getFirstPostId()   Returns the current record's "first_post_id" value
 * @method integer             getForoId()        Returns the current record's "foro_id" value
 * @method Foro                getForo()          Returns the current record's "Foro" value
 * @method Post                getPost()          Returns the current record's "Post" value
 * @method Doctrine_Collection getPosts()         Returns the current record's "Posts" collection
 * @method Tema                setFirstPostId()   Sets the current record's "first_post_id" value
 * @method Tema                setForoId()        Sets the current record's "foro_id" value
 * @method Tema                setForo()          Sets the current record's "Foro" value
 * @method Tema                setPost()          Sets the current record's "Post" value
 * @method Tema                setPosts()         Sets the current record's "Posts" collection
 * 
 * @package    achihcl
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTema extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tema');
        $this->hasColumn('first_post_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('foro_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Foro', array(
             'local' => 'foro_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Post', array(
             'local' => 'first_post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Post as Posts', array(
             'local' => 'id',
             'foreign' => 'tema_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}