<?php

/**
 * BaseForo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property longtext $descripcion
 * @property int $ntopics
 * @property int $nposts
 * @property integer $subcomision_id
 * @property Subcomision $Subcomision
 * @property Doctrine_Collection $Temas
 * @property Doctrine_Collection $Posts
 * 
 * @method text                getNombre()         Returns the current record's "nombre" value
 * @method longtext            getDescripcion()    Returns the current record's "descripcion" value
 * @method int                 getNtopics()        Returns the current record's "ntopics" value
 * @method int                 getNposts()         Returns the current record's "nposts" value
 * @method integer             getSubcomisionId()  Returns the current record's "subcomision_id" value
 * @method Subcomision         getSubcomision()    Returns the current record's "Subcomision" value
 * @method Doctrine_Collection getTemas()          Returns the current record's "Temas" collection
 * @method Doctrine_Collection getPosts()          Returns the current record's "Posts" collection
 * @method Foro                setNombre()         Sets the current record's "nombre" value
 * @method Foro                setDescripcion()    Sets the current record's "descripcion" value
 * @method Foro                setNtopics()        Sets the current record's "ntopics" value
 * @method Foro                setNposts()         Sets the current record's "nposts" value
 * @method Foro                setSubcomisionId()  Sets the current record's "subcomision_id" value
 * @method Foro                setSubcomision()    Sets the current record's "Subcomision" value
 * @method Foro                setTemas()          Sets the current record's "Temas" collection
 * @method Foro                setPosts()          Sets the current record's "Posts" collection
 * 
 * @package    achihcl
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('foro');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'longtext', null, array(
             'type' => 'longtext',
             'notnull' => true,
             ));
        $this->hasColumn('ntopics', 'int', null, array(
             'type' => 'int',
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('nposts', 'int', null, array(
             'type' => 'int',
             'notnull' => true,
             'default' => '0',
             ));
        $this->hasColumn('subcomision_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Subcomision', array(
             'local' => 'subcomision_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Tema as Temas', array(
             'local' => 'id',
             'foreign' => 'foro_id'));

        $this->hasMany('Post as Posts', array(
             'local' => 'id',
             'foreign' => 'foro_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}