<?php

/**
 * BaseBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $titulo
 * @property text $descripcion
 * @property text $enlace
 * @property boolean $activo
 * 
 * @method text    getTitulo()      Returns the current record's "titulo" value
 * @method text    getDescripcion() Returns the current record's "descripcion" value
 * @method text    getEnlace()      Returns the current record's "enlace" value
 * @method boolean getActivo()      Returns the current record's "activo" value
 * @method Banner  setTitulo()      Sets the current record's "titulo" value
 * @method Banner  setDescripcion() Sets the current record's "descripcion" value
 * @method Banner  setEnlace()      Sets the current record's "enlace" value
 * @method Banner  setActivo()      Sets the current record's "activo" value
 * 
 * @package    achihcl
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBanner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banner');
        $this->hasColumn('titulo', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('enlace', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $jcroppable0 = new Doctrine_Template_JCroppable(array(
             'images' => 
             array(
              0 => 'slide',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($jcroppable0);
        $this->actAs($timestampable0);
    }
}