<?php

/**
 * BaseEmpleo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $titulo
 * @property text $descripcion
 * @property text $ciudad
 * @property text $region
 * @property text $duracion
 * @property text $tipo
 * @property text $sueldo
 * @property text $empresa
 * @property text $nombre_contacto
 * @property text $telefono_contacto
 * @property text $email_contacto
 * 
 * @method text   getTitulo()            Returns the current record's "titulo" value
 * @method text   getDescripcion()       Returns the current record's "descripcion" value
 * @method text   getCiudad()            Returns the current record's "ciudad" value
 * @method text   getRegion()            Returns the current record's "region" value
 * @method text   getDuracion()          Returns the current record's "duracion" value
 * @method text   getTipo()              Returns the current record's "tipo" value
 * @method text   getSueldo()            Returns the current record's "sueldo" value
 * @method text   getEmpresa()           Returns the current record's "empresa" value
 * @method text   getNombreContacto()    Returns the current record's "nombre_contacto" value
 * @method text   getTelefonoContacto()  Returns the current record's "telefono_contacto" value
 * @method text   getEmailContacto()     Returns the current record's "email_contacto" value
 * @method Empleo setTitulo()            Sets the current record's "titulo" value
 * @method Empleo setDescripcion()       Sets the current record's "descripcion" value
 * @method Empleo setCiudad()            Sets the current record's "ciudad" value
 * @method Empleo setRegion()            Sets the current record's "region" value
 * @method Empleo setDuracion()          Sets the current record's "duracion" value
 * @method Empleo setTipo()              Sets the current record's "tipo" value
 * @method Empleo setSueldo()            Sets the current record's "sueldo" value
 * @method Empleo setEmpresa()           Sets the current record's "empresa" value
 * @method Empleo setNombreContacto()    Sets the current record's "nombre_contacto" value
 * @method Empleo setTelefonoContacto()  Sets the current record's "telefono_contacto" value
 * @method Empleo setEmailContacto()     Sets the current record's "email_contacto" value
 * 
 * @package    achihcl
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpleo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('empleo');
        $this->hasColumn('titulo', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('ciudad', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('region', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('duracion', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('tipo', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('sueldo', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('empresa', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('nombre_contacto', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('telefono_contacto', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('email_contacto', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}