<?php

/**
 * BaseNoticia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $titulo
 * @property longtext $cuerpo
 * 
 * @method text     getTitulo() Returns the current record's "titulo" value
 * @method longtext getCuerpo() Returns the current record's "cuerpo" value
 * @method Noticia  setTitulo() Sets the current record's "titulo" value
 * @method Noticia  setCuerpo() Sets the current record's "cuerpo" value
 * 
 * @package    achihcl
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNoticia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('noticia');
        $this->hasColumn('titulo', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('cuerpo', 'longtext', null, array(
             'type' => 'longtext',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}