<?php

/**
 * BaseEvento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property text $descripcion
 * @property text $ubicacion
 * @property timestamp $inicio_at
 * @property timestamp $fin_at
 * @property text $valor
 * @property text $afiche
 * 
 * @method text      getNombre()      Returns the current record's "nombre" value
 * @method text      getDescripcion() Returns the current record's "descripcion" value
 * @method text      getUbicacion()   Returns the current record's "ubicacion" value
 * @method timestamp getInicioAt()    Returns the current record's "inicio_at" value
 * @method timestamp getFinAt()       Returns the current record's "fin_at" value
 * @method text      getValor()       Returns the current record's "valor" value
 * @method text      getAfiche()      Returns the current record's "afiche" value
 * @method Evento    setNombre()      Sets the current record's "nombre" value
 * @method Evento    setDescripcion() Sets the current record's "descripcion" value
 * @method Evento    setUbicacion()   Sets the current record's "ubicacion" value
 * @method Evento    setInicioAt()    Sets the current record's "inicio_at" value
 * @method Evento    setFinAt()       Sets the current record's "fin_at" value
 * @method Evento    setValor()       Sets the current record's "valor" value
 * @method Evento    setAfiche()      Sets the current record's "afiche" value
 * 
 * @package    achihcl
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evento');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('ubicacion', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('inicio_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('fin_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('valor', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('afiche', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}