<?php

/**
 * BaseDoc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property text $descripcion
 * @property text $archivo
 * 
 * @method text getNombre()      Returns the current record's "nombre" value
 * @method text getDescripcion() Returns the current record's "descripcion" value
 * @method text getArchivo()     Returns the current record's "archivo" value
 * @method Doc  setNombre()      Sets the current record's "nombre" value
 * @method Doc  setDescripcion() Sets the current record's "descripcion" value
 * @method Doc  setArchivo()     Sets the current record's "archivo" value
 * 
 * @package    achihcl
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDoc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('doc');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('archivo', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}