<?php

/**
 * BasePosts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $asunto
 * @property longtext $cuerpo
 * @property integer $tema_id
 * @property integer $foro_id
 * @property Tema $Tema
 * @property Foro $Foro
 * 
 * @method text     getAsunto()  Returns the current record's "asunto" value
 * @method longtext getCuerpo()  Returns the current record's "cuerpo" value
 * @method integer  getTemaId()  Returns the current record's "tema_id" value
 * @method integer  getForoId()  Returns the current record's "foro_id" value
 * @method Tema     getTema()    Returns the current record's "Tema" value
 * @method Foro     getForo()    Returns the current record's "Foro" value
 * @method Posts    setAsunto()  Sets the current record's "asunto" value
 * @method Posts    setCuerpo()  Sets the current record's "cuerpo" value
 * @method Posts    setTemaId()  Sets the current record's "tema_id" value
 * @method Posts    setForoId()  Sets the current record's "foro_id" value
 * @method Posts    setTema()    Sets the current record's "Tema" value
 * @method Posts    setForo()    Sets the current record's "Foro" value
 * 
 * @package    achihcl
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('posts');
        $this->hasColumn('asunto', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('cuerpo', 'longtext', null, array(
             'type' => 'longtext',
             'notnull' => true,
             ));
        $this->hasColumn('tema_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('foro_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tema', array(
             'local' => 'tema_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Foro', array(
             'local' => 'foro_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}