<?php

/**
 * BaseComision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property longtext $descripcion
 * @property Doctrine_Collection $Subcomisiones
 * 
 * @method text                getNombre()        Returns the current record's "nombre" value
 * @method longtext            getDescripcion()   Returns the current record's "descripcion" value
 * @method Doctrine_Collection getSubcomisiones() Returns the current record's "Subcomisiones" collection
 * @method Comision            setNombre()        Sets the current record's "nombre" value
 * @method Comision            setDescripcion()   Sets the current record's "descripcion" value
 * @method Comision            setSubcomisiones() Sets the current record's "Subcomisiones" collection
 * 
 * @package    achihcl
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComision extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comision');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'longtext', null, array(
             'type' => 'longtext',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Subcomision as Subcomisiones', array(
             'local' => 'id',
             'foreign' => 'comision_id'));
    }
}