<?php
// auto-generated by sfViewConfigHandler
// date: 2011/08/03 12:10:47
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Asociación Chilena de Ingenieria Hospitalaria', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('jquery.twitter.css', '', array ());
  $response->addJavascript('jquery.js', '', array ());
  $response->addJavascript('easySlider1.5.js', '', array ());
  $response->addJavascript('jquery.twitter.js', '', array ());


