<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/08/03 00:56:19

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=achihcl',
  'username' => 'root',
  'password' => 'lagoranco1809',
  'name' => 'doctrine',
)),);
