<?php

/**
 * ComisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comision');
    }
}