<?php

/**
 * DocsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Docs');
    }
}