<?php

/**
 * EmpleoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpleoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpleoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Empleo');
    }
}