<?php

/**
 * ForoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Foro');
    }
}