<?php

/**
 * Link
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    achihcl
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Link extends BaseLink
{
}
