<?php

/**
 * MiembroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MiembroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MiembroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Miembro');
    }
}