<?php

/**
 * Miembro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    achihcl
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto [at] webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Miembro extends BaseMiembro
{
  public function getNombreCompleto()
  {
    return $this->getNombre() . " " . $this->getApellido();
  }
}
