<?php

/**
 * SubcomisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubcomisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubcomisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subcomision');
    }
}