# config/doctrine/schema.yml
---
Noticia:
  actAs:            { Timestampable: ~ ,Signable: ~ }
  columns:
    titulo:         { type: text, notnull: true }
    cuerpo:         { type: longtext, notnull: true }
 
Link:
  columns:
    titulo:         { type: text, notnull: true }
    descripcion:    { type: text, notnull: false }
    link:           { type: text, notnull: true }

Doc:
  actAs:            { Timestampable: ~ }
  columns:
    nombre:         { type: text, notnull: true }
    descripcion:    { type: text, notnull: false }
    archivo:        { type: text, notnull: true }