# config/doctrine/schema.yml
---
Noticia:
  actAs:            { Timestampable: ~ ,Signable: ~ }
  columns:
    titulo:         { type: text, notnull: true }
    cuerpo:         { type: longtext, notnull: true }
 
Link:
  columns:
    titulo:         { type: text, notnull: true }
    descripcion:    { type: text, notnull: false }
    link:           { type: text, notnull: true }

Doc:
  actAs:            { Timestampable: ~ }
  columns:
    nombre:         { type: text, notnull: true }
    descripcion:    { type: text, notnull: false }
    archivo:        { type: text, notnull: true }
    
Evento:
  columns:
    nombre:         { type: text, notnull: true }
    descripcion:    { type: text, notnull: true }
    ubicacion:      { type: text, notnull: true }
    inicio_at:      { type: timestamp, notnull: true }
    fin_at:         { type: timestamp, notnull: false }
    valor:          { type: text, notnull: false }
    afiche:         { type: text, notnull: false }
      