# config/doctrine/schema.yml
---
Noticia:
  actAs:            { Timestampable: ~ ,Signable: ~ }
  columns:
    titulo:         { type: text, notnull: true }
    cuerpo:         { type: longtext, notnull: true }
 
Link:
  columns:
    titulo:         { type: text, notnull: true }
    descripcion:    { type: text, notnull: false }
    link:           { type: text, notnull: true }

Doc:
  actAs:            { Timestampable: ~ }
  columns:
    nombre:         { type: text, notnull: true }
    descripcion:    { type: text, notnull: false }
    archivo:        { type: text, notnull: true }
    
Evento:
  columns:
    nombre:         { type: text, notnull: true }
    descripcion:    { type: text, notnull: true }
    ubicacion:      { type: text, notnull: true }
    inicio_at:      { type: timestamp, notnull: true }
    fin_at:         { type: timestamp, notnull: false }
    valor:          { type: text, notnull: false }
    afiche:         { type: text, notnull: false }

Miembro:
  columns:
    nombre:             { type: text, notnull: true }
    apellido:           { type: text, notnull: true }
    nacimiento_at:      { type: timestamp, notnull: false }
    rut:                { type: text, notnull: true }
    nacionalidad:       { type: text, notnull: false }
    profesion:          { type: text, notnull: false }
    especialidad:       { type: text, notnull: false }
    institucion:        { type: text, notnull: false }
    sector:             { type: text, notnull: false }
    direccion:          { type: text, notnull: false }
    comuna:             { type: text, notnull: false }
    ciudad:             { type: text, notnull: false }
    pais:               { type: text, notnull: false }
    telefono:           { type: text, notnull: false }
    celular:            { type: text, notnull: false }
    email:              { type: text, notnull: true }
    empresa:            { type: text, notnull: false }
    cargo:              { type: text, notnull: false }
    direccion_empresa:  { type: text, notnull: false }
    comuna_empresa:     { type: text, notnull: false }
    ciudad_empresa:     { type: text, notnull: false }
    pais_empresa:       { type: text, notnull: false }
    telefono_empresa:   { type: text, notnull: false }
    celular_empresa:    { type: text, notnull: false }
    email_empresa:      { type: text, notnull: false }
    isAprobado:         { type: boolean, notnull: true, default: '0' }
    rol:                { type: text, notnull: false }
    comision:           { type: text, notnull: false }
    subcomision:        { type: text, notnull: false }
    cchrc:              { type: boolean, notnull: false, default: false }

EmpresaColaboradora:
  columns:
    nombre:             { type: text, notnull: true }
    logo:               { type: text, notnull: true }
    descripcion:        { type: text, notnull: false }
    url:                { type: text, notnull: true }

Empleo:
  actAs:                { Timestampable: ~ }
  columns:
    titulo:             { type: text, notnull: true }
    descripcion:        { type: text, notnull: true }
    ciudad:             { type: text, notnull: true }
    region:             { type: text, notnull: true }
    duracion:           { type: text, notnull: false }
    tipo:               { type: text, notnull: true }
    sueldo:             { type: text, notnull: false }
    empresa:            { type: text, notnull: false }
    nombre_contacto:    { type: text, notnull: true }
    telefono_contacto:  { type: text, notnull: false }
    email_contacto:     { type: text, notnull: true }

Banner:
  actAs:
    JCroppable:
      images:     [ slide ]
    Timestampable: ~
  columns:
    titulo:       { type: text, notnull: true }
    descripcion:  { type: text, notnull: true }
    enlace:       { type: text, notnull: false }
    activo:				{ type: boolean, notnull: true, default: false }